import React, { useEffect, useState } from 'react'

import Head from 'next/head';
import styles from '../styles/Header.module.css';
import Image from 'next/image';
import ButtonColor from '../button.js';
import { useTheme, THEME_Prehistori, THEME_Standart, THEME_Future } from '../ThemeProvaider.js';

// logo тем
import LogoStandart from '../../../public/Logo.png';
import LogoFuture from '../../../public/Group (9).png'
import LogoPrehistori from '../../../public/Group (8).png'

import Icon1 from '../../../public/Vector (1).png';
import Icon2 from '../../../public/Group (6).png';
import Icon3 from '../../../public/Group 1.png';

import iconNeitral1 from '../../../public/Group (10).png';
import iconNeitral2 from '../../../public/Group 1 (2).png';
import iconNeitral3 from '../../../public/Vector (5).png';

const Header = ({ title }) => {

  const imgStandart = [Icon1, Icon2, Icon3];
  const imgNeitral = [iconNeitral1, iconNeitral2, iconNeitral3];

  const [logo, setLogo] = useState(LogoStandart);
  const [icon, setIcon] = useState(imgStandart);
  const isTheme = useTheme();

  useEffect(() => {
    switch (isTheme.theme) {
      case THEME_Prehistori: setLogo(LogoPrehistori); break;
      case THEME_Standart: setLogo(LogoStandart); break;
      case THEME_Future: setLogo(LogoFuture); break;
      default: setLogo(LogoStandart);

    }
  }, [isTheme]);
  useEffect(() => {
    switch (isTheme.theme) {
      case THEME_Future: setIcon(imgNeitral); break;
      default: setIcon(imgStandart);
    }
  }, [isTheme]);

  return (
    <>
      <div className={styles.container_header}>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </Head>
        <div className={styles.content_header}>
          <div>
            <Image src={logo} alt="Vercel Logo" />
          </div>
          <div className={styles.icon_content}>
            <div className={styles.icon_img} >
              {icon.map((item, index) => {
                return <Image src={item} alt="Vercel Logo" width={31} height={31} key={index.toString()} />
              })}
            </div>

            <div className={styles.button_color}>
              <ButtonColor name="MINT" />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Header